version: 2

sources:
  - name: globepay
    database: starlit-glider-223717
    schema: globepay
    tables:
      - name: acceptance_report
        columns:
          - name: external_ref
            tests:
                  - unique
                  - not_null
      - name: chargeback_report
        columns:
          - name: external_ref
            tests:
                  - unique
                  - not_null
